[tool.poetry]
name = "hcclient"
version = "v1.16.0"
description = "A terminal client for connecting to hack.chat"

license = "Unlicense"

authors = [
    "AnnikaV9 <carrot.moncher@gmail.com>"
]

repository = "https://github.com/AnnikaV9/hcclient"
homepage = "https://github.com/AnnikaV9/hcclient"

# README file(s) are used as the package description
readme = ["docs/README.md", "LICENSE"]

[tool.poetry.dependencies]
python = ">=3.10"
colorama = "0.4.6"
jeepney = "0.8.0"
loguru = "0.6.0"
notify-py = "0.3.42"
prompt-toolkit = "3.0.41"
termcolor = "2.4.0"
websocket-client = "1.6.4"
wsaccel = "0.6.6"
python-socks = "2.4.3"
PyYAML = "6.0.1"
wcwidth = "0.2.12"
Pygments = "2.17.2"
markdown-it-py = "3.0.0"
mdurl = "0.1.2"

[tool.poetry.scripts]
hcclient = "hcclient.__main__:main"